#define IDENTIFIER                       1
#define INTCONSTANT                      2
#define FLOATCONSTANT                    3
#define BOOLCONSTANT                     4
#define LEFT_PAREN                       5
#define RIGHT_PAREN                      6
#define LEFT_BRACKET                     7
#define RIGHT_BRACKET                    8
#define DOT                              9
#define FIELD_SELECTION                 10
#define INC_OP                          11
#define DEC_OP                          12
#define VOID                            13
#define COMMA                           14
#define FLOAT                           15
#define INT                             16
#define BOOL                            17
#define VEC2                            18
#define VEC3                            19
#define VEC4                            20
#define BVEC2                           21
#define BVEC3                           22
#define BVEC4                           23
#define IVEC2                           24
#define IVEC3                           25
#define IVEC4                           26
#define MAT2                            27
#define MAT3                            28
#define MAT4                            29
#define TYPE_NAME                       30
#define PLUS                            31
#define DASH                            32
#define BANG                            33
#define TILDE                           34
#define STAR                            35
#define SLASH                           36
#define PERCENT                         37
#define LEFT_OP                         38
#define RIGHT_OP                        39
#define LEFT_ANGLE                      40
#define RIGHT_ANGLE                     41
#define LE_OP                           42
#define GE_OP                           43
#define EQ_OP                           44
#define NE_OP                           45
#define AMPERSAND                       46
#define CARET                           47
#define VERTICAL_BAR                    48
#define AND_OP                          49
#define XOR_OP                          50
#define OR_OP                           51
#define QUESTION                        52
#define COLON                           53
#define EQUAL                           54
#define MUL_ASSIGN                      55
#define DIV_ASSIGN                      56
#define MOD_ASSIGN                      57
#define ADD_ASSIGN                      58
#define SUB_ASSIGN                      59
#define LEFT_ASSIGN                     60
#define RIGHT_ASSIGN                    61
#define AND_ASSIGN                      62
#define XOR_ASSIGN                      63
#define OR_ASSIGN                       64
#define SEMICOLON                       65
#define PRECISION                       66
#define IN                              67
#define OUT                             68
#define INOUT                           69
#define INVARIANT                       70
#define CONST                           71
#define ATTRIBUTE                       72
#define VARYING                         73
#define UNIFORM                         74
#define SAMPLER2D                       75
#define SAMPLERCUBE                     76
#define HIGH_PRECISION                  77
#define MEDIUM_PRECISION                78
#define LOW_PRECISION                   79
#define STRUCT                          80
#define LEFT_BRACE                      81
#define RIGHT_BRACE                     82
#define IF                              83
#define ELSE                            84
#define WHILE                           85
#define DO                              86
#define FOR                             87
#define CONTINUE                        88
#define BREAK                           89
#define RETURN                          90
#define DISCARD                         91
#define PREPROCESSOR_DIRECTIVE          92
